
import type { ClauseCardProps } from '../components/analyze/ClauseCard'
import pdfMake from 'pdfmake/build/pdfmake'
import * as pdfFontsModule from 'pdfmake/build/vfs_fonts'

const pdfFonts = (pdfFontsModule as any).default ?? pdfFontsModule
pdfMake.addVirtualFileSystem(pdfFonts)
import type { Content, TDocumentDefinitions } from 'pdfmake/interfaces'

const RULES_VERSION = 'AAOIFI Shariah Standards No. 8 & 9'
const M_SECTION: [number, number, number, number] = [0, 0, 0, 18]
const M_INDENT: [number, number, number, number] = [12, 0, 0, 0]
// const M_HEADING: [number, number, number, number] = [0, 14, 0, 6]

// const formatConfidence = (confidence: number) => {
//     if (confidence >= 80) return 'High Confidence'
//     if (confidence >= 60) return 'Medium Confidence'
//     return 'Low Confidence'
// }

// const formatPage = (page?: number) => page ? `Page ${page}` : 'Page unavailable'

const sanitizeFileName = (file: string) => file.replace(/\.pdf$/i, '').replace(/[^a-z0-9-_]+/gi, '-').replace(/^-|-$/g, '')

export const buildReport = ({ data, file }: { data: Record<string, ClauseCardProps[]>; file: string }) => {
    const groups = Object.entries(data ?? {})
    const clauses = groups.flatMap(([ruling, group]) =>
        (group ?? []).map((clause) => ({ ...clause, ruling: clause.ruling || ruling }))
    )
    const pages = new Set(clauses.map((clause) => clause.chunkPage).filter((page): page is number => typeof page === 'number'))
    const nonCompliant = clauses.filter((clause) => clause.suggestion === 'non-compliant').length
    const uncertain = clauses.filter((clause) => clause.suggestion === 'uncertain').length
    const breakdown = groups
        .map(([ruling, group]) => `${ruling.charAt(0).toUpperCase()}${ruling.slice(1)} (${group?.length ?? 0})`)
        .join(', ')

    const flagSection = (ruling: string, group: ClauseCardProps[]): Content[] => {
        const flags = (group ?? []).filter((clause) => clause.suggestion !== 'compliant')
        if (flags.length === 0) {
            return [{ text: 'No flagged clauses.', italics: true, color: '#666666', margin: M_SECTION }]
        }
        return flags.flatMap((clause): Content[] => [
            { text: `Page: ${clause.chunkPage}`, bold: true, margin: [0, 6, 0, 0] as const },
            { text: [
                { text: 'Excerpt: ', bold: true },
                { text: clause.chunk || 'Unavailable' },
            ], margin: M_INDENT },
            { text: [
                { text: 'Reasoning: ', bold: true },
                { text: clause.reasoning || 'Unavailable' },
            ], margin: M_INDENT },
        ])
    }

    // const document = {
    //     content: [
    //         { text: file || 'Shariah Compliance Analysis', style: 'title' },
    //         { text: `Analysis date: ${new Date().toLocaleDateString()}`, margin: [0, 0, 0, 2] },
    //         { text: `Rules version checked: ${RULES_VERSION}`, margin: [0, 0, 0, 18] },
    //         { text: 'SUMMARY', style: 'heading' },
    //         { text: `• ${clauses.length} chunks analyzed across ${pages.size} pages` },
    //         { text: `• ${nonCompliant} flagged as non-compliant, ${uncertain} flagged as uncertain` },
    //         { text: `• Breakdown: ${breakdown || 'No rulings available'}`, margin: [0, 0, 0, 18] },
    //         { text: 'RIBA FLAGS', style: 'heading' },
    //         ...flagSection('riba', groups.find(([ruling]) => ruling.toLowerCase() === 'riba')?.[1] ?? []),
    //         { text: 'GHARAR FLAGS', style: 'heading', margin: [0, 12, 0, 0] },
    //         ...flagSection('gharar', groups.find(([ruling]) => ruling.toLowerCase() === 'gharar')?.[1] ?? []),
    //         { text: 'DISCLAIMER', style: 'heading', margin: [0, 18, 0, 4] },
    //         { text: 'This report is generated by automated analysis and is intended as a preliminary screening aid. It does not constitute a formal Shariah ruling; ambiguous or flagged terms should be reviewed by a qualified Islamic finance scholar or compliance professional.' },
    //     ],
    //     styles: {
    //         title: { fontSize: 20, bold: true, color: '#604418', margin: [0, 0, 0, 8] },
    //         heading: { fontSize: 13, bold: true, color: '#604418', margin: [0, 14, 0, 6] },
    //     },
    //     defaultStyle: { fontSize: 10, lineHeight: 1.2 },
    // }

    const content: Content[] = [
        { text: file || 'Shariah Compliance Analysis', style: 'title' },
        { text: `Analysis date: ${new Date().toLocaleDateString()}`, margin: [0, 0, 0, 2] },
        { text: `Rules version checked: ${RULES_VERSION}`, margin: [0, 0, 0, 18] },
        { text: 'SUMMARY', style: 'heading' },
        { text: `• ${clauses.length} chunks analyzed across ${pages.size} pages` },
        { text: `• ${nonCompliant} flagged as non-compliant, ${uncertain} flagged as uncertain` },
        { text: `• Breakdown: ${breakdown || 'No rulings available'}`, margin: [0, 0, 0, 18] },
        { text: 'RIBA FLAGS', style: 'heading' },
        ...flagSection('riba', groups.find(([ruling]) => ruling.toLowerCase() === 'riba')?.[1] ?? []),
        { text: 'GHARAR FLAGS', style: 'heading', margin: [0, 12, 0, 0] },
        ...flagSection('gharar', groups.find(([ruling]) => ruling.toLowerCase() === 'gharar')?.[1] ?? []),
        { text: 'DISCLAIMER', style: 'heading', margin: [0, 18, 0, 4] },
        { text: 'This report is generated by automated analysis...' },
    ]

    const document: TDocumentDefinitions = {
        content,
        styles: {
            title: { fontSize: 20, bold: true, color: '#604418', margin: [0, 0, 0, 8] },
            heading: { fontSize: 13, bold: true, color: '#604418', margin: [0, 14, 0, 6] },
        },
        defaultStyle: { fontSize: 10, lineHeight: 1.2 },
    }

    const fileName = `${sanitizeFileName(file || 'shariah-analysis') || 'shariah-analysis'}-sharah_report.pdf`
    pdfMake.createPdf(document).download(fileName)

    
}